import Navbar from '@/components/Navbar';
import { CartContext } from '@/contexts/CartContext';
import Head from 'next/head';
import { useContext } from 'react';

export default function Home() {
  const { cart } = useContext(CartContext);
  console.log(cart);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <ul>
        <li>1</li>
        <li>2</li>
      </ul>
      <ol className='sss'>
        <li>1</li>
        <li>2</li>
      </ol>
    </>
  );
}
